@startuml
skinparam defaultFontName "Noto Sans JP"
state ああ

state うう
[*] --> ああ
note on link #FFF8DC
'InitialStateConditionError
<b><color:red> 「初期状態」には「条件」を設定できません
end note
ああ-->いい#FF5555 : 電源を入れる
ああ-->うう : 電源を入れる
@enduml